# Generated by Django 3.0.5 on 2020-04-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('profession', models.CharField(max_length=500, null=True)),
                ('obtained_ranks', models.IntegerField(null=True)),
                ('max_ranks', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=500, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('skills', models.TextField(null=True)),
                ('work_links', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
